// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: proto/cosmetic/cosmetic.proto

package cosmetic

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCosmeticsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCosmeticsRequest) Reset() {
	*x = ListCosmeticsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmetic_cosmetic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCosmeticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCosmeticsRequest) ProtoMessage() {}

func (x *ListCosmeticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmetic_cosmetic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCosmeticsRequest.ProtoReflect.Descriptor instead.
func (*ListCosmeticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosmetic_cosmetic_proto_rawDescGZIP(), []int{0}
}

type Cosmetics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price       int32  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Cosmetics) Reset() {
	*x = Cosmetics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmetic_cosmetic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cosmetics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cosmetics) ProtoMessage() {}

func (x *Cosmetics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmetic_cosmetic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cosmetics.ProtoReflect.Descriptor instead.
func (*Cosmetics) Descriptor() ([]byte, []int) {
	return file_proto_cosmetic_cosmetic_proto_rawDescGZIP(), []int{1}
}

func (x *Cosmetics) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cosmetics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cosmetics) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Cosmetics) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ListCosmeticsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Cosmetics `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListCosmeticsResponse) Reset() {
	*x = ListCosmeticsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmetic_cosmetic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCosmeticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCosmeticsResponse) ProtoMessage() {}

func (x *ListCosmeticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmetic_cosmetic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCosmeticsResponse.ProtoReflect.Descriptor instead.
func (*ListCosmeticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosmetic_cosmetic_proto_rawDescGZIP(), []int{2}
}

func (x *ListCosmeticsResponse) GetData() []*Cosmetics {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateCosmeticRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price       int32  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *CreateCosmeticRequest) Reset() {
	*x = CreateCosmeticRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmetic_cosmetic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCosmeticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCosmeticRequest) ProtoMessage() {}

func (x *CreateCosmeticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmetic_cosmetic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCosmeticRequest.ProtoReflect.Descriptor instead.
func (*CreateCosmeticRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosmetic_cosmetic_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCosmeticRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCosmeticRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCosmeticRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateCosmeticResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateCosmeticResponse) Reset() {
	*x = CreateCosmeticResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmetic_cosmetic_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCosmeticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCosmeticResponse) ProtoMessage() {}

func (x *CreateCosmeticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmetic_cosmetic_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCosmeticResponse.ProtoReflect.Descriptor instead.
func (*CreateCosmeticResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosmetic_cosmetic_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCosmeticResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteCosmeticRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *DeleteCosmeticRequest) Reset() {
	*x = DeleteCosmeticRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmetic_cosmetic_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCosmeticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCosmeticRequest) ProtoMessage() {}

func (x *DeleteCosmeticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmetic_cosmetic_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCosmeticRequest.ProtoReflect.Descriptor instead.
func (*DeleteCosmeticRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosmetic_cosmetic_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCosmeticRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeleteCosmeticReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteCosmeticReply) Reset() {
	*x = DeleteCosmeticReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmetic_cosmetic_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCosmeticReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCosmeticReply) ProtoMessage() {}

func (x *DeleteCosmeticReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmetic_cosmetic_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCosmeticReply.ProtoReflect.Descriptor instead.
func (*DeleteCosmeticReply) Descriptor() ([]byte, []int) {
	return file_proto_cosmetic_cosmetic_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCosmeticReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateCosmeticRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid        string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price       int32  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *UpdateCosmeticRequest) Reset() {
	*x = UpdateCosmeticRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmetic_cosmetic_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCosmeticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCosmeticRequest) ProtoMessage() {}

func (x *UpdateCosmeticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmetic_cosmetic_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCosmeticRequest.ProtoReflect.Descriptor instead.
func (*UpdateCosmeticRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosmetic_cosmetic_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCosmeticRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateCosmeticRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCosmeticRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCosmeticRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateCosmeticReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid        string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price       int32  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *UpdateCosmeticReply) Reset() {
	*x = UpdateCosmeticReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmetic_cosmetic_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCosmeticReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCosmeticReply) ProtoMessage() {}

func (x *UpdateCosmeticReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmetic_cosmetic_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCosmeticReply.ProtoReflect.Descriptor instead.
func (*UpdateCosmeticReply) Descriptor() ([]byte, []int) {
	return file_proto_cosmetic_cosmetic_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCosmeticReply) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateCosmeticReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCosmeticReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCosmeticReply) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_proto_cosmetic_cosmetic_proto protoreflect.FileDescriptor

var file_proto_cosmetic_cosmetic_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63,
	0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x63, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x1a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x16, 0x0a,
	0x14, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x67, 0x0a, 0x09, 0x43, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69,
	0x63, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x40,
	0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63,
	0x2e, 0x43, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x63, 0x0a, 0x15, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x73, 0x6d, 0x65, 0x74,
	0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x32, 0x0a, 0x16, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2b, 0x0a, 0x15, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x77, 0x0a, 0x15, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x22, 0x75, 0x0a, 0x13, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x73, 0x6d, 0x65, 0x74,
	0x69, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x32, 0xb4, 0x03, 0x0a, 0x0f, 0x43, 0x6f, 0x73, 0x6d,
	0x65, 0x74, 0x69, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x66, 0x0a, 0x0e, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x12, 0x1f, 0x2e,
	0x63, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x2e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x2e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x3a, 0x01, 0x2a, 0x2a, 0x09, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x65,
	0x74, 0x69, 0x63, 0x12, 0x66, 0x0a, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x73,
	0x6d, 0x65, 0x74, 0x69, 0x63, 0x12, 0x1f, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63,
	0x2e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69,
	0x63, 0x2e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x3a, 0x01, 0x2a,
	0x1a, 0x09, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x12, 0x69, 0x0a, 0x0e, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x12, 0x1f, 0x2e,
	0x63, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x3a, 0x01, 0x2a, 0x22, 0x09, 0x2f, 0x63, 0x6f,
	0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x12, 0x66, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f,
	0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x73, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x65, 0x74,
	0x69, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x65, 0x74,
	0x69, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e,
	0x3a, 0x01, 0x2a, 0x12, 0x09, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x42, 0x11,
	0x5a, 0x0f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x63, 0x6f, 0x73, 0x6d, 0x65, 0x74, 0x69,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_cosmetic_cosmetic_proto_rawDescOnce sync.Once
	file_proto_cosmetic_cosmetic_proto_rawDescData = file_proto_cosmetic_cosmetic_proto_rawDesc
)

func file_proto_cosmetic_cosmetic_proto_rawDescGZIP() []byte {
	file_proto_cosmetic_cosmetic_proto_rawDescOnce.Do(func() {
		file_proto_cosmetic_cosmetic_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_cosmetic_cosmetic_proto_rawDescData)
	})
	return file_proto_cosmetic_cosmetic_proto_rawDescData
}

var file_proto_cosmetic_cosmetic_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_cosmetic_cosmetic_proto_goTypes = []interface{}{
	(*ListCosmeticsRequest)(nil),   // 0: cosmetic.ListCosmeticsRequest
	(*Cosmetics)(nil),              // 1: cosmetic.Cosmetics
	(*ListCosmeticsResponse)(nil),  // 2: cosmetic.ListCosmeticsResponse
	(*CreateCosmeticRequest)(nil),  // 3: cosmetic.createCosmeticRequest
	(*CreateCosmeticResponse)(nil), // 4: cosmetic.createCosmeticResponse
	(*DeleteCosmeticRequest)(nil),  // 5: cosmetic.deleteCosmeticRequest
	(*DeleteCosmeticReply)(nil),    // 6: cosmetic.deleteCosmeticReply
	(*UpdateCosmeticRequest)(nil),  // 7: cosmetic.updateCosmeticRequest
	(*UpdateCosmeticReply)(nil),    // 8: cosmetic.updateCosmeticReply
}
var file_proto_cosmetic_cosmetic_proto_depIdxs = []int32{
	1, // 0: cosmetic.ListCosmeticsResponse.data:type_name -> cosmetic.Cosmetics
	5, // 1: cosmetic.CosmeticService.deleteCosmetic:input_type -> cosmetic.deleteCosmeticRequest
	7, // 2: cosmetic.CosmeticService.updateCosmetic:input_type -> cosmetic.updateCosmeticRequest
	3, // 3: cosmetic.CosmeticService.createCosmetic:input_type -> cosmetic.createCosmeticRequest
	0, // 4: cosmetic.CosmeticService.ListCosmetics:input_type -> cosmetic.ListCosmeticsRequest
	6, // 5: cosmetic.CosmeticService.deleteCosmetic:output_type -> cosmetic.deleteCosmeticReply
	8, // 6: cosmetic.CosmeticService.updateCosmetic:output_type -> cosmetic.updateCosmeticReply
	4, // 7: cosmetic.CosmeticService.createCosmetic:output_type -> cosmetic.createCosmeticResponse
	2, // 8: cosmetic.CosmeticService.ListCosmetics:output_type -> cosmetic.ListCosmeticsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_cosmetic_cosmetic_proto_init() }
func file_proto_cosmetic_cosmetic_proto_init() {
	if File_proto_cosmetic_cosmetic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_cosmetic_cosmetic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCosmeticsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmetic_cosmetic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cosmetics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmetic_cosmetic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCosmeticsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmetic_cosmetic_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCosmeticRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmetic_cosmetic_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCosmeticResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmetic_cosmetic_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCosmeticRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmetic_cosmetic_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCosmeticReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmetic_cosmetic_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCosmeticRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmetic_cosmetic_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCosmeticReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_cosmetic_cosmetic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cosmetic_cosmetic_proto_goTypes,
		DependencyIndexes: file_proto_cosmetic_cosmetic_proto_depIdxs,
		MessageInfos:      file_proto_cosmetic_cosmetic_proto_msgTypes,
	}.Build()
	File_proto_cosmetic_cosmetic_proto = out.File
	file_proto_cosmetic_cosmetic_proto_rawDesc = nil
	file_proto_cosmetic_cosmetic_proto_goTypes = nil
	file_proto_cosmetic_cosmetic_proto_depIdxs = nil
}
