# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cosmetic/cosmetic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from proto.google.api import (
    annotations_pb2 as proto_dot_google_dot_api_dot_annotations__pb2,
)

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1dproto/cosmetic/cosmetic.proto\x12\x08\x63osmetic\x1a"proto/google/api/annotations.proto"\x16\n\x14ListCosmeticsRequest"I\n\tCosmetics\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x05":\n\x15ListCosmeticsResponse\x12!\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x13.cosmetic.Cosmetics"I\n\x15\x63reateCosmeticRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x05")\n\x16\x63reateCosmeticResponse\x12\x0f\n\x07message\x18\x01 \x01(\t"%\n\x15\x64\x65leteCosmeticRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t"&\n\x13\x64\x65leteCosmeticReply\x12\x0f\n\x07message\x18\x01 \x01(\t"W\n\x15updateCosmeticRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x05"U\n\x13updateCosmeticReply\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x05\x32\xb1\x03\n\x0f\x43osmeticService\x12\x66\n\x0e\x64\x65leteCosmetic\x12\x1f.cosmetic.deleteCosmeticRequest\x1a\x1d.cosmetic.deleteCosmeticReply"\x14\x82\xd3\xe4\x93\x02\x0e*\t/cosmetic:\x01*\x12\x66\n\x0eupdateCosmetic\x12\x1f.cosmetic.updateCosmeticRequest\x1a\x1d.cosmetic.updateCosmeticReply"\x14\x82\xd3\xe4\x93\x02\x0e\x1a\t/cosmetic:\x01*\x12i\n\x0e\x63reateCosmetic\x12\x1f.cosmetic.createCosmeticRequest\x1a .cosmetic.createCosmeticResponse"\x14\x82\xd3\xe4\x93\x02\x0e"\t/cosmetic:\x01*\x12\x63\n\rListCosmetics\x12\x1e.cosmetic.ListCosmeticsRequest\x1a\x1f.cosmetic.ListCosmeticsResponse"\x11\x82\xd3\xe4\x93\x02\x0b\x12\t/cosmeticB\x11Z\x0f/proto;cosmeticb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "proto.cosmetic.cosmetic_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z\017/proto;cosmetic"
    _COSMETICSERVICE.methods_by_name["deleteCosmetic"]._options = None
    _COSMETICSERVICE.methods_by_name[
        "deleteCosmetic"
    ]._serialized_options = b"\202\323\344\223\002\016*\t/cosmetic:\001*"
    _COSMETICSERVICE.methods_by_name["updateCosmetic"]._options = None
    _COSMETICSERVICE.methods_by_name[
        "updateCosmetic"
    ]._serialized_options = b"\202\323\344\223\002\016\032\t/cosmetic:\001*"
    _COSMETICSERVICE.methods_by_name["createCosmetic"]._options = None
    _COSMETICSERVICE.methods_by_name[
        "createCosmetic"
    ]._serialized_options = b'\202\323\344\223\002\016"\t/cosmetic:\001*'
    _COSMETICSERVICE.methods_by_name["ListCosmetics"]._options = None
    _COSMETICSERVICE.methods_by_name[
        "ListCosmetics"
    ]._serialized_options = b"\202\323\344\223\002\013\022\t/cosmetic"
    _LISTCOSMETICSREQUEST._serialized_start = 79
    _LISTCOSMETICSREQUEST._serialized_end = 101
    _COSMETICS._serialized_start = 103
    _COSMETICS._serialized_end = 176
    _LISTCOSMETICSRESPONSE._serialized_start = 178
    _LISTCOSMETICSRESPONSE._serialized_end = 236
    _CREATECOSMETICREQUEST._serialized_start = 238
    _CREATECOSMETICREQUEST._serialized_end = 311
    _CREATECOSMETICRESPONSE._serialized_start = 313
    _CREATECOSMETICRESPONSE._serialized_end = 354
    _DELETECOSMETICREQUEST._serialized_start = 356
    _DELETECOSMETICREQUEST._serialized_end = 393
    _DELETECOSMETICREPLY._serialized_start = 395
    _DELETECOSMETICREPLY._serialized_end = 433
    _UPDATECOSMETICREQUEST._serialized_start = 435
    _UPDATECOSMETICREQUEST._serialized_end = 522
    _UPDATECOSMETICREPLY._serialized_start = 524
    _UPDATECOSMETICREPLY._serialized_end = 609
    _COSMETICSERVICE._serialized_start = 612
    _COSMETICSERVICE._serialized_end = 1045
# @@protoc_insertion_point(module_scope)
