version: '3.9'

services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: grpc-mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
    volumes:
      - "./mysql/init:/docker-entrypoint-initdb.d"
      - "./mysql/db/data:/var/lib/mysql"
      - "./mysql/db/data2:/data"
      - "./mysql/my.cnf:/etc/mysql/my.cnf"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci

  go-grpc-server:
    container_name: "go-grpc-server"
    image: golang120-go-jin-gam-rae:1.0.0
    build: .
    ports:
      - "9000:9000"
      - "8090:8090"
    volumes:
      - .:/app
    #    command: go run main.go
    command: air
    depends_on:
      - mysql

  python-api-server:
    build: ./grpc-python
    container_name: grpc-fastapi
    tty: true
    stdin_open: true
    ports:
      - "8001:80"
    depends_on:
      - mysql
      - go-grpc-server