version: '3.9'

services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
    volumes:
      - "./init:/docker-entrypoint-initdb.d"
      - "./db/data:/var/lib/mysql"
      - "./db/data2:/data"